ComicStore.WebApp/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ComicStore.WebApp.ViewModel;
using ET.ComicStore.Library;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ComicStore.WebApp.Controllers
{
    public class CartController : Controller
    {
		public FrameworkRepo ComicDB { get; set; }


		public CartController(FrameworkRepo comicDB)
		{
			ComicDB = comicDB;
		}


		// GET: Cart
		public ActionResult Index()
        {
			var cart = ComicDB.GetCart(ComicDB.GetOrders().Last().OrdersId).ToList();

			var viewmodel = new CartModelView { Cart = cart };
            return View(viewmodel);
        }


        // GET: Cart/Create
        public ActionResult Create()
        {
			var viewmodel = new CartModelView { Products = ComicDB.GetStoreProducts().ToList() };

			return View(viewmodel);
        }

        // POST: Cart/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CartModelView collection)
        {
            try
            {
				var pro = ComicDB.GetStoreProduct(collection.Product.Id);
				var product = new OrdersProduct
				{
					Name = pro.Name,
					Price = pro.Price,
					InventorySize = 1,
					OrdersId = ComicDB.GetOrderss()
				};

				ComicDB.ProuductAdded(collection.Product);
				ComicDB.AddOrderProduct(product);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        // GET: Cart/Delete/5
        public ActionResult Delete(int id)
        {
			var product = ComicDB.GetOrderProducts().First(x => x.Id == id);

			var viewmodel = new CartModelView { ProductO = product };
            return View(viewmodel);
        }

        // POST: Cart/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
				var product = ComicDB.GetOrderProducts().First(x => x.Id == id);

				ComicDB.RemoveOrderProduct(product);

				return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


		public ActionResult Place()
		{
			
			return View();
		}


		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Place(IFormCollection collection)
		{
			ComicDB.AddOrder();
			return RedirectToAction(nameof(Index));
		}

	}
}

ComicStore.WebApp/Controllers/ComicStoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ComicStore.WebApp.ViewModel;
using ET.ComicStore.Library;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ComicStore.WebApp.Controllers
{
    public class ComicStoreController : Controller
    {
        
        public FrameworkRepo ComicDB { get; set; }

         
        public ComicStoreController(FrameworkRepo comicDB)
        {
            ComicDB = comicDB;
        }


        // GET: ComicStore
        public ActionResult Index()
        {
            var stores = ComicDB.GetStores();
            var viewmodel = stores.Select(s => new ComicStoreModelView
            {
                Id = s.StoreId,
                Location = s.Location
            });
            return View(viewmodel);
        }

        // GET: ComicStore/Details/5
        public ActionResult Details(int id)
        {
            var store = ComicDB.GetStore(id);
            var viewmodel = new ComicStoreModelView
            {
                Id = store.StoreId,
                Location = store.Location
            };
            return View(viewmodel);
        }

        // GET: ComicStore/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ComicStore/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ComicStoreModelView store)
        {
            try
            {
                var stor = new ET.ComicStore.Library.ComicStore
                {
                    Location = store.Location
                };

                ComicDB.AddStore(stor);

                int stores = ComicDB.GetStores().Last().StoreId;

                

                ComicDB.AddInventory(stores);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ComicStore/Edit/5
        public ActionResult Edit(int id)
        {

            var store = ComicDB.GetStore(id);
            var viewmodel = new ComicStoreModelView
            {
                Id = store.StoreId,
                Location = store.Location
            };
            return View(viewmodel);
        }

        // POST: ComicStore/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id,  ComicStoreModelView store)
        {
            try
            {

                ComicDB.UpdateStore(id, store.Location);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(store);
            }
        }

        // GET: ComicStore/Delete/5
        public ActionResult Delete(int id)
        {
            var store = ComicDB.GetStore(id);
            var viewmodel = new ComicStoreModelView
            {
                Id = store.StoreId,
                Location = store.Location
            };
            return View(viewmodel);
        }

        // POST: ComicStore/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                ComicDB.DeleteStore(id);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ComicStore.WebApp/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ComicStore.WebApp.ViewModel;
using ET.ComicStore.Library;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ComicStore.WebApp.Controllers
{
    public class CustomerController : Controller
    {

        public FrameworkRepo ComicDB { get; set; }


        public CustomerController(FrameworkRepo comicDB)
        {
            ComicDB = comicDB;
        }
        // GET: Customer
        public ActionResult Index()
        {
            var customers = ComicDB.GetCustomers();
            var viewmodel = customers.Select(s => new CustomerModelView
            {
                Id = s.CustomerId,
                Name = s.Name,
                Email = s.Email,
                StoreId = s.StoreId
            });
            return View(viewmodel);
        }

        // GET: Customer/Details/5
        public ActionResult Details(int id)
        {
            var customer = ComicDB.GetCustomer(id);
            var viewmodel = new CustomerModelView
            {
                Id = customer.CustomerId,
                Name = customer.Name,
                Email = customer.Email,
                StoreId = customer.StoreId
            };
            return View(viewmodel);
        }

        // GET: Customer/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customer/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CustomerModelView customer)
        {
            try
            {
                var cust = new ET.ComicStore.Library.Customer
                {
                    Name = customer.Name,
                    Email = customer.Email,
                    StoreId = customer.StoreId
                };

                ComicDB.AddCustomer(cust);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Customer/Edit/5
        public ActionResult Edit(int id)
        {
            var customer = ComicDB.GetCustomer(id);
            var viewmodel = new CustomerModelView
            {
                Id = customer.CustomerId,
                Name = customer.Name,
                Email = customer.Email,
                StoreId = customer.StoreId
            };
            return View(viewmodel);
        }

        // POST: Customer/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, CustomerModelView customer)
        {
            try
            {
                var cust = new Customer
                {
                    CustomerId = id,
                    Name = customer.Name,
                    Email = customer.Email,
                    StoreId = customer.StoreId
                };
                ComicDB.UpdateCustomer(cust);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(customer);
            }
        }

        // GET: Customer/Delete/5
        public ActionResult Delete(int id)
        {
            var customer = ComicDB.GetCustomer(id);
            var viewmodel = new CustomerModelView
            {
                Id = customer.CustomerId,
                Name = customer.Name,
                Email = customer.Email,
                StoreId = customer.StoreId
            };
            return View(viewmodel);
        }

        // POST: Customer/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                ComicDB.DeleteCustomer(id);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ComicStore.WebApp/Controllers/HistoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ComicStore.WebApp.ViewModel;
using ET.ComicStore.Library;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ComicStore.WebApp.Controllers
{
	public class HistoryController : Controller
	{


		public FrameworkRepo ComicDB { get; set; }


		public HistoryController(FrameworkRepo comicDB)
		{
			ComicDB = comicDB;
		}



		// GET: History
		public ActionResult Index()
		{
			return View();
		}

		// GET: History/ShowStore
		public ActionResult ShowStore()
		{
			var viewmodel = new HistoryModelView
			{
				Stores = ComicDB.GetStores().ToList()
			};

			return View(viewmodel);
		}

		public ActionResult Store(int id)
		{
			var store = ComicDB.GetStore(id);
			var customers = ComicDB.GetCustomers();
			var orders = ComicDB.GetOrders();
			var products = ComicDB.GetOrderProducts();
			List<OrdersProduct> history = new List<OrdersProduct>();
			foreach (var customer in customers)
			{
				if (customer.StoreId == store.StoreId)
				{
					foreach (var order in orders)
					{
						if (customer.CustomerId == order.CustomerId)
						{
							foreach (var product in products)
							{
								if (product.OrdersId == order.OrdersId)
								{
									history.Add(product);
								}
							}
						}
					}
				}
			}

			var viewmodel = new HistoryModelView
			{
				Store = store,
				Products = history
			};

			return View(viewmodel);
		}


		public ActionResult ShowCustomer()
		{
			var viewmodel = new HistoryModelView
			{
				Customers = ComicDB.GetCustomers().ToList()
			};

			return View(viewmodel);
		}



		public ActionResult Customer(int id)
		{
			var customer = ComicDB.GetCustomer(id);
			var orders = ComicDB.GetOrders();
			var products = ComicDB.GetOrderProducts();
			List<OrdersProduct> history = new List<OrdersProduct>();
			foreach (var order in orders)
			{
				if (id == order.CustomerId)
				{
					foreach (var product in products)
					{
						if (product.OrdersId == order.OrdersId)
						{
							history.Add(product);
						}
					}
				}
			}



			var viewmodel = new HistoryModelView
			{
				Customer = customer,
				Products = history
			};

			return View(viewmodel);
		}


		public ActionResult ShowEarly()
		{
			var viewmodel = new HistoryModelView
			{
				Products = ComicDB.GetOrderProducts().OrderBy(x => x.Id).ToList()
			};

			return View(viewmodel);
		}


		public ActionResult ShowLate()
		{
			var viewmodel = new HistoryModelView
			{
				Products = ComicDB.GetOrderProducts().OrderByDescending(x => x.Id).ToList()
			};

			return View(viewmodel);
		}

		public ActionResult ShowCheap()
		{
			var viewmodel = new HistoryModelView
			{
				Products = ComicDB.GetOrderProducts().OrderBy(x => x.Price).ToList()
			};

			return View(viewmodel);
		}


		public ActionResult ShowExpensive()
		{
			var viewmodel = new HistoryModelView
			{
				Products = ComicDB.GetOrderProducts().OrderByDescending(x => x.Price).ToList()
			};

			return View(viewmodel);
		}


		public ActionResult ShowStats()
		{
			int count = ComicDB.GetCount();
			decimal total = ComicDB.GetTotal();
			int ocount = ComicDB.GetOrderss();
			var viewmodel = new HistoryModelView
			{
				CustomerCount = count/ ocount,
				TotalSales = total,
			};

			return View(viewmodel);
		}

	}
}

ComicStore.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ComicStore.WebApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ComicStore.WebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ComicStore" asp-action="Index">Comic Stores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StoreProducts" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="History" asp-action="Index">History</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">Cart</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - ComicStore.WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>